train:
  model_family: surrogate

paths:
  h5:
    train:
      h5_path: /scratch/project_2008261/pf_surrogate_modelling/data/deterministic/simulation_train.h5
      weight_h5: /scratch/project_2008261/pf_surrogate_modelling/data/deterministic/simulation_train.wavelet.h5
      # weight_key: wavelet_weights   # optional, default in PFPairDataset

    val:
      h5_path: /scratch/project_2008261/pf_surrogate_modelling/data/deterministic/simulation_val.h5
      # no weight_h5 here â†’ validation unweighted

  sim_map: /scratch/project_2008261/pf_surrogate_modelling/data/deterministic/sim_map.json


dataloader:
  file: /scratch/project_2008261/pf_surrogate_modelling/models/train/core/pf_dataloader.py
  class: PFPairDataset
  args:
    input_channels: [0, 1]
    target_channels: [0, 1]
    limit_per_group: 4


model:
  backbone: unet
  file: /scratch/project_2008261/pf_surrogate_modelling/models/backbones/unet_conv_att_cond.py
  class: UNet_SSA_PreSkip_Full
  params:
    n_channels: 2
    n_classes: 2
    cond_dim: 2
    in_factor: 75
    ssa_qk_ratio: 0.125
    ssa_heads: 4


diffusion:
  noise_schedule: linear
  timestep_sampler: uniform

loss:
  weight_wavelet_loss: 0.0

adaptive:
  region_selector: none
  enable_adaptive_resolution: false

conditioning:
  enabled: true
  source: field
  cond_dim: 2


loader:
  batch_size: 6
  num_workers: 12
  pin_memory: true
  overfit_n: 32    # still only applied to train_ds, val_ds is full


trainer:
  seed: 17
  deterministic: true
  device: cuda
  epochs: 2
  use_val: true          # enable validation
  out_dir: /scratch/project_2008261/pf_surrogate_modelling/runs_debug
  grad_clip: 0.0
  resume: false
  amp: {enabled: true, dtype: fp16}
  channels_last: false
  metrics: {mae: false, psnr: false}
  early_stop: {enabled: true, patience: 8, min_delta: 0.0, split: val, mode: min}
  use_wavelet_weights: true      # training loss uses wavelet weights


optim:
  name: adam
  lr: 1.0e-3
  weight_decay: 0.0
  betas: [0.9, 0.999]


sched:
  name: plateau
  factor: 0.1
  patience: 17
  threshold: 0.0
  threshold_mode: abs
  min_lr: 1.0e-8
  monitor: {split: val, mode: min}
