adaptive: {enable_adaptive_resolution: false, region_selector: none}
conditioning: {cond_dim: 2, enabled: true, source: field}
dataloader:
  args:
    input_channels: [0, 1]
    limit_per_group: 2
    target_channels: [0, 1]
  class: PFPairDataset
  file: /scratch/project_2008261/pf_surrogate_modelling/models/train/core/pf_dataloader.py
flow_matching: {sigma: 0.0}
loader: {batch_size: 2, limit_total: 324, num_workers: 2, pin_memory: true}
loss: {weight_wavelet_loss: 0.0}
model:
  backbone: uafno
  params:
    afno_depth: 4
    afno_inp_shape: [64, 64]
    afno_mlp_ratio: 4.0
    cond_dim: 3
    in_factor: 32
    n_channels: 2
    n_classes: 2
optim:
  betas: [0.9, 0.999]
  lr: 0.0005
  name: adam
  weight_decay: 0.0
paths:
  h5: {train: /scratch/project_2008261/pf_surrogate_modelling/data/stochastic/simulation_train.h5,
    val: /scratch/project_2008261/pf_surrogate_modelling/data/stochastic/simulation_val.h5}
  sim_map: /scratch/project_2008261/pf_surrogate_modelling/data/stochastic/sim_map.json
sched: {name: none}
train: {model_family: flow_matching}
trainer:
  amp: {dtype: fp16, enabled: true}
  channels_last: false
  deterministic: true
  device: cuda
  early_stop: {enabled: false}
  epochs: 1
  grad_clip: 0.0
  log_interval: 50
  metrics: {mae: false, psnr: false}
  out_dir: /scratch/project_2008261/pf_surrogate_modelling/runs_debug/flowmatch_uafno
  resume: false
  seed: 1
  use_val: true
  use_wavelet_weights: false
